FROM nginx:alpine
COPY ./dist /usr/share/nginx/html

# Support React Router by forwarding all traffic to index.html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d

EXPOSE 80
