services:
  traefik:
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.myresolver.acme.email=jannis.rosenbaum@ut.ee"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--log.level=INFO"
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.entrypoints=web,websecure"
      - "traefik.http.routers.react-app.rule=Host(`pix-w1.cloud.ut.ee`) && !PathPrefix(`/api/`)"
      - "traefik.http.services.react-app.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.react-app.middlewares=redirect-to-https"
      - "traefik.http.routers.react-app.tls.certresolver=myresolver"

    restart: always

  backend:
    build:
      context: .
      dockerfile: o2_server/Dockerfile
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.entrypoints=web,websecure"
      - "traefik.http.routers.fastapi.rule=Host(`pix-w1.cloud.ut.ee`) && PathPrefix(`/api/`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.fastapi-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.fastapi.middlewares=fastapi-stripprefix,redirect-to-https"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"

    environment:
      - DOMAIN=pix-w1.cloud.ut.ee
    restart: always
