name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Cache libspatialindex
        uses: actions/cache@v3
        id: libspatialindex-cache
        with:
          path: |
            /usr/local/lib/libspatialindex*
            /usr/local/include/spatialindex
          key: ${{ runner.os }}-libspatialindex-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-libspatialindex-

      - name: Build libspatialindex
        if: steps.libspatialindex-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/libspatialindex/libspatialindex.git /tmp/libspatialindex
          cd /tmp/libspatialindex
          cmake -DCMAKE_BUILD_TYPE=Release -DSIDX_BUILD_TESTS=OFF .
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: |
          poetry install
      - name: Run linter
        run: |
          poetry run make lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Cache libspatialindex
        uses: actions/cache@v3
        id: libspatialindex-cache
        with:
          path: |
            /usr/local/lib/libspatialindex*
            /usr/local/include/spatialindex
          key: ${{ runner.os }}-libspatialindex-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-libspatialindex-

      - name: Build libspatialindex
        if: steps.libspatialindex-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/libspatialindex/libspatialindex.git /tmp/libspatialindex
          cd /tmp/libspatialindex
          cmake -DCMAKE_BUILD_TYPE=Release -DSIDX_BUILD_TESTS=OFF .
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: |
          poetry install
      - name: Check formatting
        run: |
          poetry run ruff format --check o2 o2_server

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Cache libspatialindex
        uses: actions/cache@v3
        id: libspatialindex-cache
        with:
          path: |
            /usr/local/lib/libspatialindex*
            /usr/local/include/spatialindex
          key: ${{ runner.os }}-libspatialindex-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-libspatialindex-

      - name: Build libspatialindex
        if: steps.libspatialindex-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/libspatialindex/libspatialindex.git /tmp/libspatialindex
          cd /tmp/libspatialindex
          cmake -DCMAKE_BUILD_TYPE=Release -DSIDX_BUILD_TESTS=OFF .
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: |
          poetry install
      - name: Run type checker
        run: |
          poetry run make typecheck

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install cspell
        run: |
          npm install -g cspell
      - name: Run spell checker
        run: |
          make spell-check

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Cache libspatialindex
        uses: actions/cache@v3
        id: libspatialindex-cache
        with:
          path: |
            /usr/local/lib/libspatialindex*
            /usr/local/include/spatialindex
          key: ${{ runner.os }}-libspatialindex-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-libspatialindex-

      - name: Build libspatialindex
        if: steps.libspatialindex-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/libspatialindex/libspatialindex.git /tmp/libspatialindex
          cd /tmp/libspatialindex
          cmake -DCMAKE_BUILD_TYPE=Release -DSIDX_BUILD_TESTS=OFF .
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: |
          poetry install

      # Create directory outside the repository for coverage reports
      - name: Create coverage directory
        run: |
          mkdir -p /tmp/coverage-reports/html
          mkdir -p /tmp/coverage-reports/badges

      # Run tests with coverage (continue even if tests fail)
      - name: Run tests with coverage
        run: |
          poetry run python -m pytest --cov=o2 --cov-report=term-missing --cov-report=xml:/tmp/coverage-reports/coverage.xml --cov-report=html:/tmp/coverage-reports/html || true

      # Generate the coverage badge (even if tests failed)
      - name: Generate coverage badge
        run: |
          if [ -f /tmp/coverage-reports/coverage.xml ]; then
            COVERAGE=$(python -c "import xml.etree.ElementTree as ET; print('{:.0f}%'.format(float(ET.parse('/tmp/coverage-reports/coverage.xml').getroot().attrib['line-rate']) * 100))")
            COLOR=$(python -c "import xml.etree.ElementTree as ET; rate = float(ET.parse('/tmp/coverage-reports/coverage.xml').getroot().attrib['line-rate']); print('e05d44' if rate < 0.5 else 'dfb317' if rate < 0.75 else '97ca00')")
          else
            COVERAGE="0%"
            COLOR="e05d44"
          fi

          # Create badge with actual values instead of variables
          cat > /tmp/coverage-reports/badges/coverage.svg << EOF
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="96" height="20" role="img" aria-label="coverage: $COVERAGE">
            <title>coverage: $COVERAGE</title>
            <linearGradient id="s" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <clipPath id="r">
              <rect width="96" height="20" rx="3" fill="#fff"/>
            </clipPath>
            <g clip-path="url(#r)">
              <rect width="61" height="20" fill="#555"/>
              <rect x="61" width="35" height="20" fill="#$COLOR"/>
              <rect width="96" height="20" fill="url(#s)"/>
            </g>
            <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">
              <text aria-hidden="true" x="315" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="510">coverage</text>
              <text x="315" y="140" transform="scale(.1)" fill="#fff" textLength="510">coverage</text>
              <text aria-hidden="true" x="775" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="250">$COVERAGE</text>
              <text x="775" y="140" transform="scale(.1)" fill="#fff" textLength="250">$COVERAGE</text>
            </g>
          </svg>
          EOF

      # Save coverage report as an artifact
      - name: Save coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: /tmp/coverage-reports
          retention-days: 7

      # If main branch, deploy to GitHub Pages
      - name: Deploy coverage report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          # Move HTML report to root of deployment
          cp -r /tmp/coverage-reports/html/* /tmp/coverage-reports/
          # Keep badges directory
          mkdir -p /tmp/coverage-reports/badges

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /tmp/coverage-reports
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          commit-message: "Update coverage report [skip ci]"
